# usb
CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_BOOT=y

# sleep
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# rgb
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=0
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=10
CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=5
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

# bt
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# CONFIG_ZMK_BLE_EXPERIMENTAL_SEC=y
# CONFIG_ZMK_BLE_PASSKEY_ENTRY=y

# battery %

# increased limits
CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=96
CONFIG_ZMK_COMBO_MAX_PRESSED_COMBOS=6
CONFIG_ZMK_BEHAVIOR_HOLD_TAP_MAX_HELD=16
CONFIG_ZMK_BEHAVIOR_HOLD_TAP_MAX_CAPTURED_EVENTS=60

# mouse emu
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# 12kro
CONFIG_ZMK_HID_REPORT_TYPE_HKRO=y
CONFIG_ZMK_HID_KEYBOARD_REPORT_SIZE=12

# zmk studio
CONFIG_ZMK_STUDIO=y
